#! /bin/sh

set -e

QUARK="/usr/bin/quark"
QUARK_OPTS="-h 1.0.0.0 -p 80 -d /usr/lib/xui"
PIDFILE="/var/run/quark.pid"

test -x $QUARK || exit 0

case "$1" in
  start)
	echo "Starting Quark server"
	LD_PRELOAD=/usr/lib/libv4v-1.0.so.0.0.0 INET_IS_V4V=1 start-stop-daemon --start --background --make-pidfile --pidfile="${PIDFILE}" --quiet --oknodo --exec $QUARK -- $QUARK_OPTS
	;;
  stop)
	echo "Stopping Quark server"
	start-stop-daemon --stop --quiet --oknodo --pidfile="${PIDFILE}"
	rm -f "${PIDFILE}"
	;;

  restart)
	echo "Restarting Quark server"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile="${PIDFILE}"
	start-stop-daemon --start --background --make-pidfile --pidfile="${PIDFILE}" --quiet --oknodo --exec $QUARK -- $QUARK_OPTS
	;;

  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
